# Generated by Django 5.1 on 2024-09-02 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('cred_natural_persons', models.IntegerField()),
                ('cred_legal_entities', models.IntegerField()),
                ('deposits', models.IntegerField()),
                ('dep_natural_persons', models.IntegerField()),
                ('dep_legal_entities', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank_report_model',
                'verbose_name_plural': 'Bank_report_models',
                'db_table': 'bank_report_model',
            },
        ),
    ]
