# Generated by Django 5.1 on 2024-09-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nbu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankreportmodel',
            name='created_by',
        ),
    ]
