# Generated by Django 5.1 on 2024-09-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nbu', '0002_remove_bankreportmodel_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreportmodel',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankreportmodel',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
