# Generated by Django 5.1 on 2024-09-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nbu', '0003_bankreportmodel_month_bankreportmodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankreportmodel',
            name='month',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bankreportmodel',
            name='year',
            field=models.CharField(max_length=255),
        ),
    ]
