# Generated by Django 5.1 on 2024-09-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nbu', '0004_alter_bankreportmodel_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankreportmodel',
            name='month',
        ),
        migrations.RemoveField(
            model_name='bankreportmodel',
            name='year',
        ),
        migrations.AlterField(
            model_name='bankreportmodel',
            name='cred_legal_entities',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bankreportmodel',
            name='cred_natural_persons',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bankreportmodel',
            name='credits',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bankreportmodel',
            name='dep_legal_entities',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bankreportmodel',
            name='dep_natural_persons',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bankreportmodel',
            name='deposits',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
