# Generated by Django 5.1 on 2024-09-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nbu', '0005_remove_bankreportmodel_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreportmodel',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
