# Generated by Django 5.1 on 2024-09-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nbu', '0006_bankreportmodel_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreportmodel',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
