# Generated by Django 5.1 on 2024-09-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nbu', '0007_bankreportmodel_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankreportmodel',
            name='year',
        ),
    ]
