# Generated by Django 5.1 on 2024-09-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nbu', '0008_remove_bankreportmodel_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankreportmodel',
            name='month',
        ),
    ]
